-- Discovery Database Schema
-- Run with: sqlite3 discovery.db < init-discovery-db.sql

-- Briefs: Initial feature ideas
CREATE TABLE IF NOT EXISTS briefs (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  problem_statement TEXT,
  initial_thoughts TEXT,
  priority INTEGER DEFAULT 2,  -- 1=critical, 2=high, 3=medium, 4=low
  status TEXT DEFAULT 'draft', -- draft, in_discovery, spec_ready, approved, exported
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT,
  exported_epic_id TEXT        -- Links to beads epic after approval
);

-- Interview Questions: Generated by Claude during discovery
CREATE TABLE IF NOT EXISTS interview_questions (
  id TEXT PRIMARY KEY,
  brief_id TEXT REFERENCES briefs(id),
  question TEXT NOT NULL,
  category TEXT,               -- technical, business, ux, scope
  answer TEXT,
  answered_at TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);

-- SME Reviews: Findings from specialized agents
CREATE TABLE IF NOT EXISTS sme_reviews (
  id TEXT PRIMARY KEY,
  brief_id TEXT REFERENCES briefs(id),
  agent_type TEXT NOT NULL,    -- technical-sme, business-sme, ux-sme
  findings TEXT,               -- JSON or structured text
  recommendations TEXT,
  concerns TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);

-- Specs: Synthesized specifications
CREATE TABLE IF NOT EXISTS specs (
  id TEXT PRIMARY KEY,
  brief_id TEXT REFERENCES briefs(id),
  title TEXT NOT NULL,
  description TEXT,
  acceptance_criteria TEXT,    -- JSON array
  design_notes TEXT,
  task_breakdown TEXT,         -- JSON array of proposed tasks
  status TEXT DEFAULT 'draft', -- draft, review, approved, exported
  approved_at TEXT,
  exported_epic_id TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);

-- Workflow Events: Audit trail
CREATE TABLE IF NOT EXISTS workflow_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  brief_id TEXT,
  event_type TEXT,             -- created, discovery_started, question_answered, etc.
  details TEXT,                -- JSON with event-specific data
  created_at TEXT DEFAULT (datetime('now'))
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_briefs_status ON briefs(status);
CREATE INDEX IF NOT EXISTS idx_questions_brief ON interview_questions(brief_id);
CREATE INDEX IF NOT EXISTS idx_reviews_brief ON sme_reviews(brief_id);
CREATE INDEX IF NOT EXISTS idx_specs_brief ON specs(brief_id);
CREATE INDEX IF NOT EXISTS idx_events_brief ON workflow_events(brief_id);
CREATE INDEX IF NOT EXISTS idx_events_type ON workflow_events(event_type);
